// List is required to compile the resources into the game when it loads.
// Dynamically loading it has bad results with sounds overtaking each other, even with the wait variable.


/////////////
//VOX WORDS//
/////////////
// A large dict containing all sound clips and their relevant trigger string. Used for VOX announcements.


var/static/list/vox_words = list(
"a" = 'sound/vox/a.wav',
"accelerating" = 'sound/vox/accelerating.wav',
"accelerator" = 'sound/vox/accelerator.wav',
"accepted" = 'sound/vox/accepted.wav',
"access" = 'sound/vox/access.wav',
"acknowledge" = 'sound/vox/acknowledge.wav',
"acknowledged" = 'sound/vox/acknowledged.wav',
"acquired" = 'sound/vox/acquired.wav',
"acquisition" = 'sound/vox/acquisition.wav',
"across" = 'sound/vox/across.wav',
"activate" = 'sound/vox/activate.wav',
"activated" = 'sound/vox/activated.wav',
"activity" = 'sound/vox/activity.wav',
"adios" = 'sound/vox/adios.wav',
"administration" = 'sound/vox/administration.wav',
"advanced" = 'sound/vox/advanced.wav',
"after" = 'sound/vox/after.wav',
"agent" = 'sound/vox/agent.wav',
"alarm" = 'sound/vox/alarm.wav',
"alert" = 'sound/vox/alert.wav',
"alien" = 'sound/vox/alien.wav',
"aligned" = 'sound/vox/aligned.wav',
"all" = 'sound/vox/all.wav',
"alpha" = 'sound/vox/alpha.wav',
"am" = 'sound/vox/am.wav',
"amigo" = 'sound/vox/amigo.wav',
"ammunition" = 'sound/vox/ammunition.wav',
"an" = 'sound/vox/an.wav',
"and" = 'sound/vox/and.wav',
"announcement" = 'sound/vox/announcement.wav',
"anomalous" = 'sound/vox/anomalous.wav',
"antenna" = 'sound/vox/antenna.wav',
"any" = 'sound/vox/any.wav',
"apprehend" = 'sound/vox/apprehend.wav',
"approach" = 'sound/vox/approach.wav',
"are" = 'sound/vox/are.wav',
"area" = 'sound/vox/area.wav',
"arm" = 'sound/vox/arm.wav',
"armed" = 'sound/vox/armed.wav',
"armor" = 'sound/vox/armor.wav',
"armory" = 'sound/vox/armory.wav',
"arrest" = 'sound/vox/arrest.wav',
"ass" = 'sound/vox/ass.wav',
"at" = 'sound/vox/at.wav',
"atomic" = 'sound/vox/atomic.wav',
"attention" = 'sound/vox/attention.wav',
"authorize" = 'sound/vox/authorize.wav',
"authorized" = 'sound/vox/authorized.wav',
"automatic" = 'sound/vox/automatic.wav',
"away" = 'sound/vox/away.wav',
"b" = 'sound/vox/b.wav',
"back" = 'sound/vox/back.wav',
"backman" = 'sound/vox/backman.wav',
"bad" = 'sound/vox/bad.wav',
"bag" = 'sound/vox/bag.wav',
"bailey" = 'sound/vox/bailey.wav',
"barracks" = 'sound/vox/barracks.wav',
"base" = 'sound/vox/base.wav',
"bay" = 'sound/vox/bay.wav',
"be" = 'sound/vox/be.wav',
"been" = 'sound/vox/been.wav',
"before" = 'sound/vox/before.wav',
"beyond" = 'sound/vox/beyond.wav',
"biohazard" = 'sound/vox/biohazard.wav',
"biological" = 'sound/vox/biological.wav',
"birdwell" = 'sound/vox/birdwell.wav',
"noticealert" = 'sound/vox/bizwarn.wav',
"black" = 'sound/vox/black.wav',
"blast" = 'sound/vox/blast.wav',
"blocked" = 'sound/vox/blocked.wav',
"bloop" = 'sound/vox/bloop.wav',
"blue" = 'sound/vox/blue.wav',
"bottom" = 'sound/vox/bottom.wav',
"bravo" = 'sound/vox/bravo.wav',
"breach" = 'sound/vox/breach.wav',
"breached" = 'sound/vox/breached.wav',
"break" = 'sound/vox/break.wav',
"bridge" = 'sound/vox/bridge.wav',
"bust" = 'sound/vox/bust.wav',
"but" = 'sound/vox/but.wav',
"button" = 'sound/vox/button.wav',
"noticebuzzer" = 'sound/vox/buzwarn.wav',
"bypass" = 'sound/vox/bypass.wav',
"c" = 'sound/vox/c.wav',
"cable" = 'sound/vox/cable.wav',
"call" = 'sound/vox/call.wav',
"called" = 'sound/vox/called.wav',
"canal" = 'sound/vox/canal.wav',
"cap" = 'sound/vox/cap.wav',
"captain" = 'sound/vox/captain.wav',
"capture" = 'sound/vox/capture.wav',
"ceiling" = 'sound/vox/ceiling.wav',
"celsius" = 'sound/vox/celsius.wav',
"center" = 'sound/vox/center.wav',
"centi" = 'sound/vox/centi.wav',
"central" = 'sound/vox/central.wav',
"chamber" = 'sound/vox/chamber.wav',
"charlie" = 'sound/vox/charlie.wav',
"check" = 'sound/vox/check.wav',
"checkpoint" = 'sound/vox/checkpoint.wav',
"chemical" = 'sound/vox/chemical.wav',
"cleanup" = 'sound/vox/cleanup.wav',
"clear" = 'sound/vox/clear.wav',
"clearance" = 'sound/vox/clearance.wav',
"close" = 'sound/vox/close.wav',
"code" = 'sound/vox/code.wav',
"coded" = 'sound/vox/coded.wav',
"collider" = 'sound/vox/collider.wav',
"command" = 'sound/vox/command.wav',
"communication" = 'sound/vox/communication.wav',
"complex" = 'sound/vox/complex.wav',
"computer" = 'sound/vox/computer.wav',
"condition" = 'sound/vox/condition.wav',
"containment" = 'sound/vox/containment.wav',
"contamination" = 'sound/vox/contamination.wav',
"control" = 'sound/vox/control.wav',
"coolant" = 'sound/vox/coolant.wav',
"coomer" = 'sound/vox/coomer.wav',
"core" = 'sound/vox/core.wav',
"correct" = 'sound/vox/correct.wav',
"corridor" = 'sound/vox/corridor.wav',
"crew" = 'sound/vox/crew.wav',
"cross" = 'sound/vox/cross.wav',
"cryogenic" = 'sound/vox/cryogenic.wav',
"d" = 'sound/vox/d.wav',
"noticefailure" = 'sound/vox/dadeda.wav',
"damage" = 'sound/vox/damage.wav',
"damaged" = 'sound/vox/damaged.wav',
"danger" = 'sound/vox/danger.wav',
"day" = 'sound/vox/day.wav',
"deactivated" = 'sound/vox/deactivated.wav',
"decompression" = 'sound/vox/decompression.wav',
"decontamination" = 'sound/vox/decontamination.wav',
"noticenotice" = 'sound/vox/deeoo.wav',
"defense" = 'sound/vox/defense.wav',
"degrees" = 'sound/vox/degrees.wav',
"delta" = 'sound/vox/delta.wav',
"denied" = 'sound/vox/denied.wav',
"deploy" = 'sound/vox/deploy.wav',
"deployed" = 'sound/vox/deployed.wav',
"destroy" = 'sound/vox/destroy.wav',
"destroyed" = 'sound/vox/destroyed.wav',
"detain" = 'sound/vox/detain.wav',
"detected" = 'sound/vox/detected.wav',
"detonation" = 'sound/vox/detonation.wav',
"device" = 'sound/vox/device.wav',
"did" = 'sound/vox/did.wav',
"die" = 'sound/vox/die.wav',
"dimensional" = 'sound/vox/dimensional.wav',
"dirt" = 'sound/vox/dirt.wav',
"disengaged" = 'sound/vox/disengaged.wav',
"dish" = 'sound/vox/dish.wav',
"disposal" = 'sound/vox/disposal.wav',
"distance" = 'sound/vox/distance.wav',
"distortion" = 'sound/vox/distortion.wav',
"do" = 'sound/vox/do.wav',
"doctor" = 'sound/vox/doctor.wav',
"noticegeneric" = 'sound/vox/doop.wav',
"door" = 'sound/vox/door.wav',
"down" = 'sound/vox/down.wav',
"dual" = 'sound/vox/dual.wav',
"duct" = 'sound/vox/duct.wav',
"e" = 'sound/vox/e.wav',
"east" = 'sound/vox/east.wav',
"echo" = 'sound/vox/echo.wav',
"ed" = 'sound/vox/ed.wav',
"effect" = 'sound/vox/effect.wav',
"egress" = 'sound/vox/egress.wav',
"eight" = 'sound/vox/eight.wav',
"eighteen" = 'sound/vox/eighteen.wav',
"eighty" = 'sound/vox/eighty.wav',
"electric" = 'sound/vox/electric.wav',
"electromagnetic" = 'sound/vox/electromagnetic.wav',
"elevator" = 'sound/vox/elevator.wav',
"eleven" = 'sound/vox/eleven.wav',
"eliminate" = 'sound/vox/eliminate.wav',
"emergency" = 'sound/vox/emergency.wav',
"energy" = 'sound/vox/energy.wav',
"engage" = 'sound/vox/engage.wav',
"engaged" = 'sound/vox/engaged.wav',
"engine" = 'sound/vox/engine.wav',
"enter" = 'sound/vox/enter.wav',
"entry" = 'sound/vox/entry.wav',
"environment" = 'sound/vox/environment.wav',
"error" = 'sound/vox/error.wav',
"escape" = 'sound/vox/escape.wav',
"evacuate" = 'sound/vox/evacuate.wav',
"exchange" = 'sound/vox/exchange.wav',
"exit" = 'sound/vox/exit.wav',
"expect" = 'sound/vox/expect.wav',
"experiment" = 'sound/vox/experiment.wav',
"experimental" = 'sound/vox/experimental.wav',
"explode" = 'sound/vox/explode.wav',
"explosion" = 'sound/vox/explosion.wav',
"exposure" = 'sound/vox/exposure.wav',
"exterminate" = 'sound/vox/exterminate.wav',
"extinguish" = 'sound/vox/extinguish.wav',
"extinguisher" = 'sound/vox/extinguisher.wav',
"extreme" = 'sound/vox/extreme.wav',
"f" = 'sound/vox/f.wav',
"facility" = 'sound/vox/facility.wav',
"fahrenheit" = 'sound/vox/fahrenheit.wav',
"failed" = 'sound/vox/failed.wav',
"failure" = 'sound/vox/failure.wav',
"farthest" = 'sound/vox/farthest.wav',
"fast" = 'sound/vox/fast.wav',
"feet" = 'sound/vox/feet.wav',
"field" = 'sound/vox/field.wav',
"fifteen" = 'sound/vox/fifteen.wav',
"fifth" = 'sound/vox/fifth.wav',
"fifty" = 'sound/vox/fifty.wav',
"final" = 'sound/vox/final.wav',
"fine" = 'sound/vox/fine.wav',
"fire" = 'sound/vox/fire.wav',
"first" = 'sound/vox/first.wav',
"five" = 'sound/vox/five.wav',
"flooding" = 'sound/vox/flooding.wav',
"floor" = 'sound/vox/floor.wav',
"fool" = 'sound/vox/fool.wav',
"for" = 'sound/vox/for.wav',
"forbidden" = 'sound/vox/forbidden.wav',
"force" = 'sound/vox/force.wav',
"forms" = 'sound/vox/forms.wav',
"found" = 'sound/vox/found.wav',
"four" = 'sound/vox/four.wav',
"fourteen" = 'sound/vox/fourteen.wav',
"fourth" = 'sound/vox/fourth.wav',
"fourty" = 'sound/vox/fourty.wav',
"foxtrot" = 'sound/vox/foxtrot.wav',
"freeman" = 'sound/vox/freeman.wav',
"freezer" = 'sound/vox/freezer.wav',
"from" = 'sound/vox/from.wav',
"front" = 'sound/vox/front.wav',
"fuel" = 'sound/vox/fuel.wav',
"g" = 'sound/vox/g.wav',
"get" = 'sound/vox/get.wav',
"go" = 'sound/vox/go.wav',
"going" = 'sound/vox/going.wav',
"good" = 'sound/vox/good.wav',
"goodbye" = 'sound/vox/goodbye.wav',
"gordon" = 'sound/vox/gordon.wav',
"got" = 'sound/vox/got.wav',
"government" = 'sound/vox/government.wav',
"granted" = 'sound/vox/granted.wav',
"great" = 'sound/vox/great.wav',
"green" = 'sound/vox/green.wav',
"grenade" = 'sound/vox/grenade.wav',
"guard" = 'sound/vox/guard.wav',
"gulf" = 'sound/vox/gulf.wav',
"gun" = 'sound/vox/gun.wav',
"guthrie" = 'sound/vox/guthrie.wav',
"handling" = 'sound/vox/handling.wav',
"hangar" = 'sound/vox/hangar.wav',
"has" = 'sound/vox/has.wav',
"have" = 'sound/vox/have.wav',
"hazard" = 'sound/vox/hazard.wav',
"head" = 'sound/vox/head.wav',
"health" = 'sound/vox/health.wav',
"heat" = 'sound/vox/heat.wav',
"helicopter" = 'sound/vox/helicopter.wav',
"helium" = 'sound/vox/helium.wav',
"hello" = 'sound/vox/hello.wav',
"help" = 'sound/vox/help.wav',
"here" = 'sound/vox/here.wav',
"hide" = 'sound/vox/hide.wav',
"high" = 'sound/vox/high.wav',
"highest" = 'sound/vox/highest.wav',
"hit" = 'sound/vox/hit.wav',
"hole" = 'sound/vox/hole.wav',
"hostile" = 'sound/vox/hostile.wav',
"hot" = 'sound/vox/hot.wav',
"hotel" = 'sound/vox/hotel.wav',
"hour" = 'sound/vox/hour.wav',
"hours" = 'sound/vox/hours.wav',
"hundred" = 'sound/vox/hundred.wav',
"hydro" = 'sound/vox/hydro.wav',
"i" = 'sound/vox/i.wav',
"idiot" = 'sound/vox/idiot.wav',
"illegal" = 'sound/vox/illegal.wav',
"immediate" = 'sound/vox/immediate.wav',
"immediately" = 'sound/vox/immediately.wav',
"in" = 'sound/vox/in.wav',
"inches" = 'sound/vox/inches.wav',
"india" = 'sound/vox/india.wav',
"ing" = 'sound/vox/ing.wav',
"inoperative" = 'sound/vox/inoperative.wav',
"inside" = 'sound/vox/inside.wav',
"inspection" = 'sound/vox/inspection.wav',
"inspector" = 'sound/vox/inspector.wav',
"interchange" = 'sound/vox/interchange.wav',
"intruder" = 'sound/vox/intruder.wav',
"invallid" = 'sound/vox/invallid.wav',
"invasion" = 'sound/vox/invasion.wav',
"is" = 'sound/vox/is.wav',
"it" = 'sound/vox/it.wav',
"johnson" = 'sound/vox/johnson.wav',
"juliet" = 'sound/vox/juliet.wav',
"key" = 'sound/vox/key.wav',
"kill" = 'sound/vox/kill.wav',
"kilo" = 'sound/vox/kilo.wav',
"kit" = 'sound/vox/kit.wav',
"lab" = 'sound/vox/lab.wav',
"lambda" = 'sound/vox/lambda.wav',
"laser" = 'sound/vox/laser.wav',
"last" = 'sound/vox/last.wav',
"launch" = 'sound/vox/launch.wav',
"leak" = 'sound/vox/leak.wav',
"leave" = 'sound/vox/leave.wav',
"left" = 'sound/vox/left.wav',
"legal" = 'sound/vox/legal.wav',
"level" = 'sound/vox/level.wav',
"lever" = 'sound/vox/lever.wav',
"lie" = 'sound/vox/lie.wav',
"lieutenant" = 'sound/vox/lieutenant.wav',
"life" = 'sound/vox/life.wav',
"light" = 'sound/vox/light.wav',
"lima" = 'sound/vox/lima.wav',
"liquid" = 'sound/vox/liquid.wav',
"loading" = 'sound/vox/loading.wav',
"locate" = 'sound/vox/locate.wav',
"located" = 'sound/vox/located.wav',
"location" = 'sound/vox/location.wav',
"lock" = 'sound/vox/lock.wav',
"locked" = 'sound/vox/locked.wav',
"locker" = 'sound/vox/locker.wav',
"lockout" = 'sound/vox/lockout.wav',
"lower" = 'sound/vox/lower.wav',
"lowest" = 'sound/vox/lowest.wav',
"magnetic" = 'sound/vox/magnetic.wav',
"main" = 'sound/vox/main.wav',
"maintenance" = 'sound/vox/maintenance.wav',
"malfunction" = 'sound/vox/malfunction.wav',
"man" = 'sound/vox/man.wav',
"mass" = 'sound/vox/mass.wav',
"materials" = 'sound/vox/materials.wav',
"maximum" = 'sound/vox/maximum.wav',
"may" = 'sound/vox/may.wav',
"medical" = 'sound/vox/medical.wav',
"men" = 'sound/vox/men.wav',
"mercy" = 'sound/vox/mercy.wav',
"mesa" = 'sound/vox/mesa.wav',
"message" = 'sound/vox/message.wav',
"meter" = 'sound/vox/meter.wav',
"micro" = 'sound/vox/micro.wav',
"middle" = 'sound/vox/middle.wav',
"mike" = 'sound/vox/mike.wav',
"miles" = 'sound/vox/miles.wav',
"military" = 'sound/vox/military.wav',
"milli" = 'sound/vox/milli.wav',
"million" = 'sound/vox/million.wav',
"minefield" = 'sound/vox/minefield.wav',
"minimum" = 'sound/vox/minimum.wav',
"minutes" = 'sound/vox/minutes.wav',
"mister" = 'sound/vox/mister.wav',
"mode" = 'sound/vox/mode.wav',
"motor" = 'sound/vox/motor.wav',
"motorpool" = 'sound/vox/motorpool.wav',
"move" = 'sound/vox/move.wav',
"must" = 'sound/vox/must.wav',
"nearest" = 'sound/vox/nearest.wav',
"nice" = 'sound/vox/nice.wav',
"nine" = 'sound/vox/nine.wav',
"nineteen" = 'sound/vox/nineteen.wav',
"ninety" = 'sound/vox/ninety.wav',
"no" = 'sound/vox/no.wav',
"nominal" = 'sound/vox/nominal.wav',
"north" = 'sound/vox/north.wav',
"not" = 'sound/vox/not.wav',
"november" = 'sound/vox/november.wav',
"now" = 'sound/vox/now.wav',
"number" = 'sound/vox/number.wav',
"objective" = 'sound/vox/objective.wav',
"observation" = 'sound/vox/observation.wav',
"of" = 'sound/vox/of.wav',
"officer" = 'sound/vox/officer.wav',
"ok" = 'sound/vox/ok.wav',
"on" = 'sound/vox/on.wav',
"one" = 'sound/vox/one.wav',
"open" = 'sound/vox/open.wav',
"operating" = 'sound/vox/operating.wav',
"operations" = 'sound/vox/operations.wav',
"operative" = 'sound/vox/operative.wav',
"option" = 'sound/vox/option.wav',
"order" = 'sound/vox/order.wav',
"organic" = 'sound/vox/organic.wav',
"oscar" = 'sound/vox/oscar.wav',
"out" = 'sound/vox/out.wav',
"outside" = 'sound/vox/outside.wav',
"over" = 'sound/vox/over.wav',
"overload" = 'sound/vox/overload.wav',
"override" = 'sound/vox/override.wav',
"pacify" = 'sound/vox/pacify.wav',
"pain" = 'sound/vox/pain.wav',
"pal" = 'sound/vox/pal.wav',
"panel" = 'sound/vox/panel.wav',
"percent" = 'sound/vox/percent.wav',
"perimeter" = 'sound/vox/perimeter.wav',
"permitted" = 'sound/vox/permitted.wav',
"personnel" = 'sound/vox/personnel.wav',
"pipe" = 'sound/vox/pipe.wav',
"plant" = 'sound/vox/plant.wav',
"platform" = 'sound/vox/platform.wav',
"please" = 'sound/vox/please.wav',
"point" = 'sound/vox/point.wav',
"portal" = 'sound/vox/portal.wav',
"power" = 'sound/vox/power.wav',
"presence" = 'sound/vox/presence.wav',
"press" = 'sound/vox/press.wav',
"primary" = 'sound/vox/primary.wav',
"proceed" = 'sound/vox/proceed.wav',
"processing" = 'sound/vox/processing.wav',
"progress" = 'sound/vox/progress.wav',
"proper" = 'sound/vox/proper.wav',
"propulsion" = 'sound/vox/propulsion.wav',
"prosecute" = 'sound/vox/prosecute.wav',
"protective" = 'sound/vox/protective.wav',
"push" = 'sound/vox/push.wav',
"quantum" = 'sound/vox/quantum.wav',
"quebec" = 'sound/vox/quebec.wav',
"question" = 'sound/vox/question.wav',
"questioning" = 'sound/vox/questioning.wav',
"quick" = 'sound/vox/quick.wav',
"quit" = 'sound/vox/quit.wav',
"radiation" = 'sound/vox/radiation.wav',
"radioactive" = 'sound/vox/radioactive.wav',
"rads" = 'sound/vox/rads.wav',
"rapid" = 'sound/vox/rapid.wav',
"reach" = 'sound/vox/reach.wav',
"reached" = 'sound/vox/reached.wav',
"reactor" = 'sound/vox/reactor.wav',
"red" = 'sound/vox/red.wav',
"relay" = 'sound/vox/relay.wav',
"released" = 'sound/vox/released.wav',
"remaining" = 'sound/vox/remaining.wav',
"renegade" = 'sound/vox/renegade.wav',
"repair" = 'sound/vox/repair.wav',
"report" = 'sound/vox/report.wav',
"reports" = 'sound/vox/reports.wav',
"required" = 'sound/vox/required.wav',
"research" = 'sound/vox/research.wav',
"resevoir" = 'sound/vox/resevoir.wav',
"resistance" = 'sound/vox/resistance.wav',
"right" = 'sound/vox/right.wav',
"rocket" = 'sound/vox/rocket.wav',
"roger" = 'sound/vox/roger.wav',
"romeo" = 'sound/vox/romeo.wav',
"room" = 'sound/vox/room.wav',
"round" = 'sound/vox/round.wav',
"run" = 'sound/vox/run.wav',
"safe" = 'sound/vox/safe.wav',
"safety" = 'sound/vox/safety.wav',
"sargeant" = 'sound/vox/sargeant.wav',
"satellite" = 'sound/vox/satellite.wav',
"save" = 'sound/vox/save.wav',
"science" = 'sound/vox/science.wav',
"scream" = 'sound/vox/scream.wav',
"screen" = 'sound/vox/screen.wav',
"search" = 'sound/vox/search.wav',
"second" = 'sound/vox/second.wav',
"secondary" = 'sound/vox/secondary.wav',
"seconds" = 'sound/vox/seconds.wav',
"sector" = 'sound/vox/sector.wav',
"secure" = 'sound/vox/secure.wav',
"secured" = 'sound/vox/secured.wav',
"security" = 'sound/vox/security.wav',
"select" = 'sound/vox/select.wav',
"selected" = 'sound/vox/selected.wav',
"service" = 'sound/vox/service.wav',
"seven" = 'sound/vox/seven.wav',
"seventeen" = 'sound/vox/seventeen.wav',
"seventy" = 'sound/vox/seventy.wav',
"severe" = 'sound/vox/severe.wav',
"sewage" = 'sound/vox/sewage.wav',
"sewer" = 'sound/vox/sewer.wav',
"shield" = 'sound/vox/shield.wav',
"shipment" = 'sound/vox/shipment.wav',
"shock" = 'sound/vox/shock.wav',
"shoot" = 'sound/vox/shoot.wav',
"shower" = 'sound/vox/shower.wav',
"shut" = 'sound/vox/shut.wav',
"side" = 'sound/vox/side.wav',
"sierra" = 'sound/vox/sierra.wav',
"sight" = 'sound/vox/sight.wav',
"silo" = 'sound/vox/silo.wav',
"six" = 'sound/vox/six.wav',
"sixteen" = 'sound/vox/sixteen.wav',
"sixty" = 'sound/vox/sixty.wav',
"slime" = 'sound/vox/slime.wav',
"slow" = 'sound/vox/slow.wav',
"soldier" = 'sound/vox/soldier.wav',
"some" = 'sound/vox/some.wav',
"someone" = 'sound/vox/someone.wav',
"something" = 'sound/vox/something.wav',
"son" = 'sound/vox/son.wav',
"sorry" = 'sound/vox/sorry.wav',
"south" = 'sound/vox/south.wav',
"squad" = 'sound/vox/squad.wav',
"square" = 'sound/vox/square.wav',
"stairway" = 'sound/vox/stairway.wav',
"status" = 'sound/vox/status.wav',
"sterile" = 'sound/vox/sterile.wav',
"sterilization" = 'sound/vox/sterilization.wav',
"storage" = 'sound/vox/storage.wav',
"sub" = 'sound/vox/sub.wav',
"subsurface" = 'sound/vox/subsurface.wav',
"sudden" = 'sound/vox/sudden.wav',
"suit" = 'sound/vox/suit.wav',
"superconducting" = 'sound/vox/superconducting.wav',
"supercooled" = 'sound/vox/supercooled.wav',
"supply" = 'sound/vox/supply.wav',
"surface" = 'sound/vox/surface.wav',
"surrender" = 'sound/vox/surrender.wav',
"surround" = 'sound/vox/surround.wav',
"surrounded" = 'sound/vox/surrounded.wav',
"switch" = 'sound/vox/switch.wav',
"system" = 'sound/vox/system.wav',
"systems" = 'sound/vox/systems.wav',
"tactical" = 'sound/vox/tactical.wav',
"take" = 'sound/vox/take.wav',
"talk" = 'sound/vox/talk.wav',
"tango" = 'sound/vox/tango.wav',
"tank" = 'sound/vox/tank.wav',
"target" = 'sound/vox/target.wav',
"team" = 'sound/vox/team.wav',
"temperature" = 'sound/vox/temperature.wav',
"temporal" = 'sound/vox/temporal.wav',
"ten" = 'sound/vox/ten.wav',
"terminal" = 'sound/vox/terminal.wav',
"terminated" = 'sound/vox/terminated.wav',
"termination" = 'sound/vox/termination.wav',
"test" = 'sound/vox/test.wav',
"that" = 'sound/vox/that.wav',
"the" = 'sound/vox/the.wav',
"then" = 'sound/vox/then.wav',
"there" = 'sound/vox/there.wav',
"third" = 'sound/vox/third.wav',
"thirteen" = 'sound/vox/thirteen.wav',
"thirty" = 'sound/vox/thirty.wav',
"this" = 'sound/vox/this.wav',
"those" = 'sound/vox/those.wav',
"thousand" = 'sound/vox/thousand.wav',
"threat" = 'sound/vox/threat.wav',
"three" = 'sound/vox/three.wav',
"through" = 'sound/vox/through.wav',
"time" = 'sound/vox/time.wav',
"to" = 'sound/vox/to.wav',
"top" = 'sound/vox/top.wav',
"topside" = 'sound/vox/topside.wav',
"touch" = 'sound/vox/touch.wav',
"towards" = 'sound/vox/towards.wav',
"track" = 'sound/vox/track.wav',
"train" = 'sound/vox/train.wav',
"transportation" = 'sound/vox/transportation.wav',
"truck" = 'sound/vox/truck.wav',
"tunnel" = 'sound/vox/tunnel.wav',
"turn" = 'sound/vox/turn.wav',
"turret" = 'sound/vox/turret.wav',
"twelve" = 'sound/vox/twelve.wav',
"twenty" = 'sound/vox/twenty.wav',
"two" = 'sound/vox/two.wav',
"unauthorized" = 'sound/vox/unauthorized.wav',
"under" = 'sound/vox/under.wav',
"uniform" = 'sound/vox/uniform.wav',
"unlocked" = 'sound/vox/unlocked.wav',
"until" = 'sound/vox/until.wav',
"up" = 'sound/vox/up.wav',
"upper" = 'sound/vox/upper.wav',
"uranium" = 'sound/vox/uranium.wav',
"us" = 'sound/vox/us.wav',
"usa" = 'sound/vox/usa.wav',
"use" = 'sound/vox/use.wav',
"used" = 'sound/vox/used.wav',
"user" = 'sound/vox/user.wav',
"vacate" = 'sound/vox/vacate.wav',
"valid" = 'sound/vox/valid.wav',
"vapor" = 'sound/vox/vapor.wav',
"vent" = 'sound/vox/vent.wav',
"ventillation" = 'sound/vox/ventillation.wav',
"victor" = 'sound/vox/victor.wav',
"violated" = 'sound/vox/violated.wav',
"violation" = 'sound/vox/violation.wav',
"voltage" = 'sound/vox/voltage.wav',
//"vox_login" = 'sound/vox/vox_login.wav',
"walk" = 'sound/vox/walk.wav',
"wall" = 'sound/vox/wall.wav',
"want" = 'sound/vox/want.wav',
"wanted" = 'sound/vox/wanted.wav',
"warm" = 'sound/vox/warm.wav',
"warn" = 'sound/vox/warn.wav',
"warning" = 'sound/vox/warning.wav',
"waste" = 'sound/vox/waste.wav',
"water" = 'sound/vox/water.wav',
"we" = 'sound/vox/we.wav',
"weapon" = 'sound/vox/weapon.wav',
"west" = 'sound/vox/west.wav',
"whiskey" = 'sound/vox/whiskey.wav',
"white" = 'sound/vox/white.wav',
"wilco" = 'sound/vox/wilco.wav',
"will" = 'sound/vox/will.wav',
"with" = 'sound/vox/with.wav',
"without" = 'sound/vox/without.wav',
"noticewoop" = 'sound/vox/woop.wav',
"xeno" = 'sound/vox/xeno.wav',
"yankee" = 'sound/vox/yankee.wav',
"yards" = 'sound/vox/yards.wav',
"year" = 'sound/vox/year.wav',
"yellow" = 'sound/vox/yellow.wav',
"yes" = 'sound/vox/yes.wav',
"you" = 'sound/vox/you.wav',
"your" = 'sound/vox/your.wav',
"yourself" = 'sound/vox/yourself.wav',
"zero" = 'sound/vox/zero.wav',
"zone" = 'sound/vox/zone.wav',
"zulu" = 'sound/vox/zulu.wav',
"," = 'sound/vox/_comma.wav',
"." = 'sound/vox/_period.wav',
)


//////////////////
//VOX SOUNDCLIPS//
//////////////////
// A large list containing all soundclips on their own. Used for caching.

var/static/list/vox_soundclips = list(
'sound/vox/a.wav',
'sound/vox/accelerating.wav',
'sound/vox/accelerator.wav',
'sound/vox/accepted.wav',
'sound/vox/access.wav',
'sound/vox/acknowledge.wav',
'sound/vox/acknowledged.wav',
'sound/vox/acquired.wav',
'sound/vox/acquisition.wav',
'sound/vox/across.wav',
'sound/vox/activate.wav',
'sound/vox/activated.wav',
'sound/vox/activity.wav',
'sound/vox/adios.wav',
'sound/vox/administration.wav',
'sound/vox/advanced.wav',
'sound/vox/after.wav',
'sound/vox/agent.wav',
'sound/vox/alarm.wav',
'sound/vox/alert.wav',
'sound/vox/alien.wav',
'sound/vox/aligned.wav',
'sound/vox/all.wav',
'sound/vox/alpha.wav',
'sound/vox/am.wav',
'sound/vox/amigo.wav',
'sound/vox/ammunition.wav',
'sound/vox/an.wav',
'sound/vox/and.wav',
'sound/vox/announcement.wav',
'sound/vox/anomalous.wav',
'sound/vox/antenna.wav',
'sound/vox/any.wav',
'sound/vox/apprehend.wav',
'sound/vox/approach.wav',
'sound/vox/are.wav',
'sound/vox/area.wav',
'sound/vox/arm.wav',
'sound/vox/armed.wav',
'sound/vox/armor.wav',
'sound/vox/armory.wav',
'sound/vox/arrest.wav',
'sound/vox/ass.wav',
'sound/vox/at.wav',
'sound/vox/atomic.wav',
'sound/vox/attention.wav',
'sound/vox/authorize.wav',
'sound/vox/authorized.wav',
'sound/vox/automatic.wav',
'sound/vox/away.wav',
'sound/vox/b.wav',
'sound/vox/back.wav',
'sound/vox/backman.wav',
'sound/vox/bad.wav',
'sound/vox/bag.wav',
'sound/vox/bailey.wav',
'sound/vox/barracks.wav',
'sound/vox/base.wav',
'sound/vox/bay.wav',
'sound/vox/be.wav',
'sound/vox/been.wav',
'sound/vox/before.wav',
'sound/vox/beyond.wav',
'sound/vox/biohazard.wav',
'sound/vox/biological.wav',
'sound/vox/birdwell.wav',
'sound/vox/bizwarn.wav',
'sound/vox/black.wav',
'sound/vox/blast.wav',
'sound/vox/blocked.wav',
'sound/vox/bloop.wav',
'sound/vox/blue.wav',
'sound/vox/bottom.wav',
'sound/vox/bravo.wav',
'sound/vox/breach.wav',
'sound/vox/breached.wav',
'sound/vox/break.wav',
'sound/vox/bridge.wav',
'sound/vox/bust.wav',
'sound/vox/but.wav',
'sound/vox/button.wav',
'sound/vox/buzwarn.wav',
'sound/vox/bypass.wav',
'sound/vox/c.wav',
'sound/vox/cable.wav',
'sound/vox/call.wav',
'sound/vox/called.wav',
'sound/vox/canal.wav',
'sound/vox/cap.wav',
'sound/vox/captain.wav',
'sound/vox/capture.wav',
'sound/vox/ceiling.wav',
'sound/vox/celsius.wav',
'sound/vox/center.wav',
'sound/vox/centi.wav',
'sound/vox/central.wav',
'sound/vox/chamber.wav',
'sound/vox/charlie.wav',
'sound/vox/check.wav',
'sound/vox/checkpoint.wav',
'sound/vox/chemical.wav',
'sound/vox/cleanup.wav',
'sound/vox/clear.wav',
'sound/vox/clearance.wav',
'sound/vox/close.wav',
'sound/vox/code.wav',
'sound/vox/coded.wav',
'sound/vox/collider.wav',
'sound/vox/command.wav',
'sound/vox/communication.wav',
'sound/vox/complex.wav',
'sound/vox/computer.wav',
'sound/vox/condition.wav',
'sound/vox/containment.wav',
'sound/vox/contamination.wav',
'sound/vox/control.wav',
'sound/vox/coolant.wav',
'sound/vox/coomer.wav',
'sound/vox/core.wav',
'sound/vox/correct.wav',
'sound/vox/corridor.wav',
'sound/vox/crew.wav',
'sound/vox/cross.wav',
'sound/vox/cryogenic.wav',
'sound/vox/d.wav',
'sound/vox/dadeda.wav',
'sound/vox/damage.wav',
'sound/vox/damaged.wav',
'sound/vox/danger.wav',
'sound/vox/day.wav',
'sound/vox/deactivated.wav',
'sound/vox/decompression.wav',
'sound/vox/decontamination.wav',
'sound/vox/deeoo.wav',
'sound/vox/defense.wav',
'sound/vox/degrees.wav',
'sound/vox/delta.wav',
'sound/vox/denied.wav',
'sound/vox/deploy.wav',
'sound/vox/deployed.wav',
'sound/vox/destroy.wav',
'sound/vox/destroyed.wav',
'sound/vox/detain.wav',
'sound/vox/detected.wav',
'sound/vox/detonation.wav',
'sound/vox/device.wav',
'sound/vox/did.wav',
'sound/vox/die.wav',
'sound/vox/dimensional.wav',
'sound/vox/dirt.wav',
'sound/vox/disengaged.wav',
'sound/vox/dish.wav',
'sound/vox/disposal.wav',
'sound/vox/distance.wav',
'sound/vox/distortion.wav',
'sound/vox/do.wav',
'sound/vox/doctor.wav',
'sound/vox/doop.wav',
'sound/vox/door.wav',
'sound/vox/down.wav',
'sound/vox/dual.wav',
'sound/vox/duct.wav',
'sound/vox/e.wav',
'sound/vox/east.wav',
'sound/vox/echo.wav',
'sound/vox/ed.wav',
'sound/vox/effect.wav',
'sound/vox/egress.wav',
'sound/vox/eight.wav',
'sound/vox/eighteen.wav',
'sound/vox/eighty.wav',
'sound/vox/electric.wav',
'sound/vox/electromagnetic.wav',
'sound/vox/elevator.wav',
'sound/vox/eleven.wav',
'sound/vox/eliminate.wav',
'sound/vox/emergency.wav',
'sound/vox/energy.wav',
'sound/vox/engage.wav',
'sound/vox/engaged.wav',
'sound/vox/engine.wav',
'sound/vox/enter.wav',
'sound/vox/entry.wav',
'sound/vox/environment.wav',
'sound/vox/error.wav',
'sound/vox/escape.wav',
'sound/vox/evacuate.wav',
'sound/vox/exchange.wav',
'sound/vox/exit.wav',
'sound/vox/expect.wav',
'sound/vox/experiment.wav',
'sound/vox/experimental.wav',
'sound/vox/explode.wav',
'sound/vox/explosion.wav',
'sound/vox/exposure.wav',
'sound/vox/exterminate.wav',
'sound/vox/extinguish.wav',
'sound/vox/extinguisher.wav',
'sound/vox/extreme.wav',
'sound/vox/f.wav',
'sound/vox/facility.wav',
'sound/vox/fahrenheit.wav',
'sound/vox/failed.wav',
'sound/vox/failure.wav',
'sound/vox/farthest.wav',
'sound/vox/fast.wav',
'sound/vox/feet.wav',
'sound/vox/field.wav',
'sound/vox/fifteen.wav',
'sound/vox/fifth.wav',
'sound/vox/fifty.wav',
'sound/vox/final.wav',
'sound/vox/fine.wav',
'sound/vox/fire.wav',
'sound/vox/first.wav',
'sound/vox/five.wav',
'sound/vox/flooding.wav',
'sound/vox/floor.wav',
'sound/vox/fool.wav',
'sound/vox/for.wav',
'sound/vox/forbidden.wav',
'sound/vox/force.wav',
'sound/vox/forms.wav',
'sound/vox/found.wav',
'sound/vox/four.wav',
'sound/vox/fourteen.wav',
'sound/vox/fourth.wav',
'sound/vox/fourty.wav',
'sound/vox/foxtrot.wav',
'sound/vox/freeman.wav',
'sound/vox/freezer.wav',
'sound/vox/from.wav',
'sound/vox/front.wav',
'sound/vox/fuel.wav',
'sound/vox/g.wav',
'sound/vox/get.wav',
'sound/vox/go.wav',
'sound/vox/going.wav',
'sound/vox/good.wav',
'sound/vox/goodbye.wav',
'sound/vox/gordon.wav',
'sound/vox/got.wav',
'sound/vox/government.wav',
'sound/vox/granted.wav',
'sound/vox/great.wav',
'sound/vox/green.wav',
'sound/vox/grenade.wav',
'sound/vox/guard.wav',
'sound/vox/gulf.wav',
'sound/vox/gun.wav',
'sound/vox/guthrie.wav',
'sound/vox/handling.wav',
'sound/vox/hangar.wav',
'sound/vox/has.wav',
'sound/vox/have.wav',
'sound/vox/hazard.wav',
'sound/vox/head.wav',
'sound/vox/health.wav',
'sound/vox/heat.wav',
'sound/vox/helicopter.wav',
'sound/vox/helium.wav',
'sound/vox/hello.wav',
'sound/vox/help.wav',
'sound/vox/here.wav',
'sound/vox/hide.wav',
'sound/vox/high.wav',
'sound/vox/highest.wav',
'sound/vox/hit.wav',
'sound/vox/hole.wav',
'sound/vox/hostile.wav',
'sound/vox/hot.wav',
'sound/vox/hotel.wav',
'sound/vox/hour.wav',
'sound/vox/hours.wav',
'sound/vox/hundred.wav',
'sound/vox/hydro.wav',
'sound/vox/i.wav',
'sound/vox/idiot.wav',
'sound/vox/illegal.wav',
'sound/vox/immediate.wav',
'sound/vox/immediately.wav',
'sound/vox/in.wav',
'sound/vox/inches.wav',
'sound/vox/india.wav',
'sound/vox/ing.wav',
'sound/vox/inoperative.wav',
'sound/vox/inside.wav',
'sound/vox/inspection.wav',
'sound/vox/inspector.wav',
'sound/vox/interchange.wav',
'sound/vox/intruder.wav',
'sound/vox/invallid.wav',
'sound/vox/invasion.wav',
'sound/vox/is.wav',
'sound/vox/it.wav',
'sound/vox/johnson.wav',
'sound/vox/juliet.wav',
'sound/vox/key.wav',
'sound/vox/kill.wav',
'sound/vox/kilo.wav',
'sound/vox/kit.wav',
'sound/vox/lab.wav',
'sound/vox/lambda.wav',
'sound/vox/laser.wav',
'sound/vox/last.wav',
'sound/vox/launch.wav',
'sound/vox/leak.wav',
'sound/vox/leave.wav',
'sound/vox/left.wav',
'sound/vox/legal.wav',
'sound/vox/level.wav',
'sound/vox/lever.wav',
'sound/vox/lie.wav',
'sound/vox/lieutenant.wav',
'sound/vox/life.wav',
'sound/vox/light.wav',
'sound/vox/lima.wav',
'sound/vox/liquid.wav',
'sound/vox/loading.wav',
'sound/vox/locate.wav',
'sound/vox/located.wav',
'sound/vox/location.wav',
'sound/vox/lock.wav',
'sound/vox/locked.wav',
'sound/vox/locker.wav',
'sound/vox/lockout.wav',
'sound/vox/lower.wav',
'sound/vox/lowest.wav',
'sound/vox/magnetic.wav',
'sound/vox/main.wav',
'sound/vox/maintenance.wav',
'sound/vox/malfunction.wav',
'sound/vox/man.wav',
'sound/vox/mass.wav',
'sound/vox/materials.wav',
'sound/vox/maximum.wav',
'sound/vox/may.wav',
'sound/vox/medical.wav',
'sound/vox/men.wav',
'sound/vox/mercy.wav',
'sound/vox/mesa.wav',
'sound/vox/message.wav',
'sound/vox/meter.wav',
'sound/vox/micro.wav',
'sound/vox/middle.wav',
'sound/vox/mike.wav',
'sound/vox/miles.wav',
'sound/vox/military.wav',
'sound/vox/milli.wav',
'sound/vox/million.wav',
'sound/vox/minefield.wav',
'sound/vox/minimum.wav',
'sound/vox/minutes.wav',
'sound/vox/mister.wav',
'sound/vox/mode.wav',
'sound/vox/motor.wav',
'sound/vox/motorpool.wav',
'sound/vox/move.wav',
'sound/vox/must.wav',
'sound/vox/nearest.wav',
'sound/vox/nice.wav',
'sound/vox/nine.wav',
'sound/vox/nineteen.wav',
'sound/vox/ninety.wav',
'sound/vox/no.wav',
'sound/vox/nominal.wav',
'sound/vox/north.wav',
'sound/vox/not.wav',
'sound/vox/november.wav',
'sound/vox/now.wav',
'sound/vox/number.wav',
'sound/vox/objective.wav',
'sound/vox/observation.wav',
'sound/vox/of.wav',
'sound/vox/officer.wav',
'sound/vox/ok.wav',
'sound/vox/on.wav',
'sound/vox/one.wav',
'sound/vox/open.wav',
'sound/vox/operating.wav',
'sound/vox/operations.wav',
'sound/vox/operative.wav',
'sound/vox/option.wav',
'sound/vox/order.wav',
'sound/vox/organic.wav',
'sound/vox/oscar.wav',
'sound/vox/out.wav',
'sound/vox/outside.wav',
'sound/vox/over.wav',
'sound/vox/overload.wav',
'sound/vox/override.wav',
'sound/vox/pacify.wav',
'sound/vox/pain.wav',
'sound/vox/pal.wav',
'sound/vox/panel.wav',
'sound/vox/percent.wav',
'sound/vox/perimeter.wav',
'sound/vox/permitted.wav',
'sound/vox/personnel.wav',
'sound/vox/pipe.wav',
'sound/vox/plant.wav',
'sound/vox/platform.wav',
'sound/vox/please.wav',
'sound/vox/point.wav',
'sound/vox/portal.wav',
'sound/vox/power.wav',
'sound/vox/presence.wav',
'sound/vox/press.wav',
'sound/vox/primary.wav',
'sound/vox/proceed.wav',
'sound/vox/processing.wav',
'sound/vox/progress.wav',
'sound/vox/proper.wav',
'sound/vox/propulsion.wav',
'sound/vox/prosecute.wav',
'sound/vox/protective.wav',
'sound/vox/push.wav',
'sound/vox/quantum.wav',
'sound/vox/quebec.wav',
'sound/vox/question.wav',
'sound/vox/questioning.wav',
'sound/vox/quick.wav',
'sound/vox/quit.wav',
'sound/vox/radiation.wav',
'sound/vox/radioactive.wav',
'sound/vox/rads.wav',
'sound/vox/rapid.wav',
'sound/vox/reach.wav',
'sound/vox/reached.wav',
'sound/vox/reactor.wav',
'sound/vox/red.wav',
'sound/vox/relay.wav',
'sound/vox/released.wav',
'sound/vox/remaining.wav',
'sound/vox/renegade.wav',
'sound/vox/repair.wav',
'sound/vox/report.wav',
'sound/vox/reports.wav',
'sound/vox/required.wav',
'sound/vox/research.wav',
'sound/vox/resevoir.wav',
'sound/vox/resistance.wav',
'sound/vox/right.wav',
'sound/vox/rocket.wav',
'sound/vox/roger.wav',
'sound/vox/romeo.wav',
'sound/vox/room.wav',
'sound/vox/round.wav',
'sound/vox/run.wav',
'sound/vox/safe.wav',
'sound/vox/safety.wav',
'sound/vox/sargeant.wav',
'sound/vox/satellite.wav',
'sound/vox/save.wav',
'sound/vox/science.wav',
'sound/vox/scream.wav',
'sound/vox/screen.wav',
'sound/vox/search.wav',
'sound/vox/second.wav',
'sound/vox/secondary.wav',
'sound/vox/seconds.wav',
'sound/vox/sector.wav',
'sound/vox/secure.wav',
'sound/vox/secured.wav',
'sound/vox/security.wav',
'sound/vox/select.wav',
'sound/vox/selected.wav',
'sound/vox/service.wav',
'sound/vox/seven.wav',
'sound/vox/seventeen.wav',
'sound/vox/seventy.wav',
'sound/vox/severe.wav',
'sound/vox/sewage.wav',
'sound/vox/sewer.wav',
'sound/vox/shield.wav',
'sound/vox/shipment.wav',
'sound/vox/shock.wav',
'sound/vox/shoot.wav',
'sound/vox/shower.wav',
'sound/vox/shut.wav',
'sound/vox/side.wav',
'sound/vox/sierra.wav',
'sound/vox/sight.wav',
'sound/vox/silo.wav',
'sound/vox/six.wav',
'sound/vox/sixteen.wav',
'sound/vox/sixty.wav',
'sound/vox/slime.wav',
'sound/vox/slow.wav',
'sound/vox/soldier.wav',
'sound/vox/some.wav',
'sound/vox/someone.wav',
'sound/vox/something.wav',
'sound/vox/son.wav',
'sound/vox/sorry.wav',
'sound/vox/south.wav',
'sound/vox/squad.wav',
'sound/vox/square.wav',
'sound/vox/stairway.wav',
'sound/vox/status.wav',
'sound/vox/sterile.wav',
'sound/vox/sterilization.wav',
'sound/vox/storage.wav',
'sound/vox/sub.wav',
'sound/vox/subsurface.wav',
'sound/vox/sudden.wav',
'sound/vox/suit.wav',
'sound/vox/superconducting.wav',
'sound/vox/supercooled.wav',
'sound/vox/supply.wav',
'sound/vox/surface.wav',
'sound/vox/surrender.wav',
'sound/vox/surround.wav',
'sound/vox/surrounded.wav',
'sound/vox/switch.wav',
'sound/vox/system.wav',
'sound/vox/systems.wav',
'sound/vox/tactical.wav',
'sound/vox/take.wav',
'sound/vox/talk.wav',
'sound/vox/tango.wav',
'sound/vox/tank.wav',
'sound/vox/target.wav',
'sound/vox/team.wav',
'sound/vox/temperature.wav',
'sound/vox/temporal.wav',
'sound/vox/ten.wav',
'sound/vox/terminal.wav',
'sound/vox/terminated.wav',
'sound/vox/termination.wav',
'sound/vox/test.wav',
'sound/vox/that.wav',
'sound/vox/the.wav',
'sound/vox/then.wav',
'sound/vox/there.wav',
'sound/vox/third.wav',
'sound/vox/thirteen.wav',
'sound/vox/thirty.wav',
'sound/vox/this.wav',
'sound/vox/those.wav',
'sound/vox/thousand.wav',
'sound/vox/threat.wav',
'sound/vox/three.wav',
'sound/vox/through.wav',
'sound/vox/time.wav',
'sound/vox/to.wav',
'sound/vox/top.wav',
'sound/vox/topside.wav',
'sound/vox/touch.wav',
'sound/vox/towards.wav',
'sound/vox/track.wav',
'sound/vox/train.wav',
'sound/vox/transportation.wav',
'sound/vox/truck.wav',
'sound/vox/tunnel.wav',
'sound/vox/turn.wav',
'sound/vox/turret.wav',
'sound/vox/twelve.wav',
'sound/vox/twenty.wav',
'sound/vox/two.wav',
'sound/vox/unauthorized.wav',
'sound/vox/under.wav',
'sound/vox/uniform.wav',
'sound/vox/unlocked.wav',
'sound/vox/until.wav',
'sound/vox/up.wav',
'sound/vox/upper.wav',
'sound/vox/uranium.wav',
'sound/vox/us.wav',
'sound/vox/usa.wav',
'sound/vox/use.wav',
'sound/vox/used.wav',
'sound/vox/user.wav',
'sound/vox/vacate.wav',
'sound/vox/valid.wav',
'sound/vox/vapor.wav',
'sound/vox/vent.wav',
'sound/vox/ventillation.wav',
'sound/vox/victor.wav',
'sound/vox/violated.wav',
'sound/vox/violation.wav',
'sound/vox/voltage.wav',
'sound/vox/vox_login.wav',
'sound/vox/walk.wav',
'sound/vox/wall.wav',
'sound/vox/want.wav',
'sound/vox/wanted.wav',
'sound/vox/warm.wav',
'sound/vox/warn.wav',
'sound/vox/warning.wav',
'sound/vox/waste.wav',
'sound/vox/water.wav',
'sound/vox/we.wav',
'sound/vox/weapon.wav',
'sound/vox/west.wav',
'sound/vox/whiskey.wav',
'sound/vox/white.wav',
'sound/vox/wilco.wav',
'sound/vox/will.wav',
'sound/vox/with.wav',
'sound/vox/without.wav',
'sound/vox/woop.wav',
'sound/vox/xeno.wav',
'sound/vox/yankee.wav',
'sound/vox/yards.wav',
'sound/vox/year.wav',
'sound/vox/yellow.wav',
'sound/vox/yes.wav',
'sound/vox/you.wav',
'sound/vox/your.wav',
'sound/vox/yourself.wav',
'sound/vox/zero.wav',
'sound/vox/zone.wav',
'sound/vox/zulu.wav',
'sound/vox/_comma.wav',
'sound/vox/_period.wav'
)


